<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCyZqKx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCyZqKx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWCyZqKx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWCyZqKx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWCyZqKx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WCyZqKx',
    'container.build_id' => '17e3715d',
    'container.build_time' => 1699295992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCyZqKx');
